<!doctype html>
<html lang="es">
	<?php include "_head.php";?>
	<body>
		<?php include "_header.php";?>
		<section class="encuesta">
			<div class="container">
				<div class="row mb-5">
					<div class="col text-center">
						<h1>Pólitica de Privacidad</h1>
					</div>
				</div>
				<div class="row mb-5">
					<div class="col">
						<p><strong>IDENTIDAD Y DOMICILIO DEL RESPONSABLE</strong><br>En&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>, licenciatario de la marca Naturistas Ziloé (en adelante las “Marcas”) con domicilio en Calle Chicle #674, Col. Glorias del Colli, Código Postal 45010 en la Ciudad de Zapopan, Jalisco. Los datos personales y personales sensibles, de nuestros consumidores y posibles consumidores (en adelante “datos personales”), son tratados de forma estrictamente privada y confidencial, por lo que la obtención, tratamiento, transferencia y ejercicio de los derechos derivados de dichos datos personales, se hace mediante un uso adecuado, legítimo y lícito, salvaguardando permanentemente los principios de licitud, consentimiento, calidad, información, proporcionalidad, responsabilidad, lealtad y finalidad, de conformidad con lo dispuesto por la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, su Reglamento y disposiciones secundarias.</p>
						<p><strong>OBTENCIÓN DE DATOS PERSONALES Y FINALIDADES DE SU TRATAMIENTO.</strong><br>En&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>&nbsp;estamos comprometidos con salvaguardar la privacidad de sus datos personales y mantener una relación estrecha y activa con nuestros consumidores y posibles consumidores por eso además de éste Aviso, aplicamos nuestra&nbsp;<a href="https://naturistasziloe.com/index.php/politica-de-privacidad/">Política de Privacidad</a>, te invitamos a conocerla.</p>
						<p>A continuación, señalamos expresa y limitativamente los datos que podremos recabar de usted como consumidor y posible consumidor:</p>
						<p>Datos Personales de identificación y contacto:</p>
						<figure class="wp-block-table"><table><tbody><tr><td>•</td><td>Nombre, apellido paterno y materno, género, edad, fecha de nacimiento, domicilio, código postal, número telefónico, número celular y correo electrónico.</td></tr></tbody></table></figure>
						<p>Con respecto de los datos personales antes mencionados, se garantiza un tratamiento, ya sea directa o indirectamente a través de&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>, sus subsidiarias, afiliadas o empresas relacionadas, y sus terceros proveedores de servicios con quienes tiene una relación jurídica; obran y tratan datos personales por cuenta de<strong>&nbsp;RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>, así como, en su caso, por las autoridades competentes, para las finalidades que dieron origen y son necesarias para la existencia, mantenimiento y cumplimiento de la relación jurídica con sus consumidores, que son las siguientes:</p>
						<figure class="wp-block-table"><table><tbody><tr><td>•</td><td>Para dar cumplimiento a la relación jurídica establecida con usted derivado de la adquisición de alguno de los productos de las Marcas al proveerle información sobre el mismo.</td></tr><tr><td>•</td><td>Para atender quejas o recomendaciones respecto del uso y aplicación de los productos de las Marcas.</td></tr></tbody></table></figure>
						<p>De manera adicional,&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>, podrá tratar sus datos personales para las siguientes finalidades distintas o secundarias, que no son necesarias para la existencia, mantenimiento y cumplimiento de la relación jurídica con sus consumidores, pero que nos permiten brindarle una mejor atención:</p>
						<figure class="wp-block-table"><table><tbody><tr><td>•</td><td>Mercadotecnia, publicidad, prospección comercial, evaluación de nuestros productos y servicios relacionados con las Marcas, incluyendo el envío de muestras gratis y/o artículos promocionales.</td></tr></tbody></table></figure>
						<p>La negativa otorgada para el tratamiento de sus datos personales para las finalidades distintas o secundarias señaladas previamente, no podrá ser un motivo para que le neguemos los productos o servicios derivados de la adquisición de los productos o servicios que adquiere o contrata con nosotros.</p>
						<p>Derivado de lo anterior,&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>, le informa que, en caso de que usted no desee que sus datos personales sean tratados para las finalidades distintas o secundarias que se precisan en el presente documento, le solicitamos nos envíe un correo electrónico a la dirección jose_heredia@ziloe.com.mx, a efecto de que nuestro “Departamento de Datos Personales” documente dicha situación mediante su inscripción en nuestro listado de exclusión denominado “Contactos que no desean envío de publicidad”.</p>
						<p>Es importante mencionar que, en caso de que<strong>&nbsp;RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>, pretendiera utilizar sus datos personales sensibles para las finalidades secundarias descritas con anterioridad, previo a su tratamiento, solicitará su consentimiento expreso y por escrito de conformidad con la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, su Reglamento y demás disposiciones secundarias obligatorias, de lo contrario no hará uso de los mismos para estos fines.</p>
						<p>Los datos personales que usted proporcione a<strong>&nbsp;RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.&nbsp;</strong>serán tratados exclusivamente para las finalidades descritas, se les tratará de forma confidencial y exclusivamente en la medida en que éstos sean estrictamente necesarios para cumplir la finalidad para la cual hubieren sido recabados.</p>
						<p>Para prevenir el acceso no autorizado a sus datos personales y con el fin de asegurar que la información sea utilizada para los fines establecidos en este aviso de privacidad, hemos implementado procedimientos físicos, electrónicos y administrativos, utilizando tecnologías avanzadas que limitan el uso o divulgación de sus datos, permitiéndonos tratarlos debidamente y prohibiendo extraer de las oficinas de&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>, de forma no autorizada, cualquier tipo de información que contenga datos personales.</p>
						<p><strong>TRANSFERENCIAS DE DATOS PERSONALES A TERCEROS.</strong><br>Por medio de este aviso de privacidad,&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>&nbsp;le informa que podrá transferir sus datos personales de identificación y contacto (no sensibles) a terceros nacionales o extranjeros; tales como a sus subsidiarias, afiliadas o empresas relacionadas y proveedores de servicios con los que mantenga una relación jurídica, para las siguientes finalidades:</p>
						<figure class="wp-block-table"><table><tbody><tr><td>•</td><td>Mercadotecnia, publicidad y prospección comercial.</td></tr></tbody></table></figure>
						<p>Derivado de lo anterior&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.&nbsp;</strong>le informa que, en caso de que usted no desee que sus datos personales sean transferidos a los terceros que se mencionan en el presente apartado y para las finalidades aquí descritas, le solicitamos atentamente nos envíe un correo electrónico a la dirección&nbsp;<a href="https://shampoohuichol.com/index.php/contactanos/">jose_heredia@ziloe.com.mx</a>, a efecto de que nuestro “Departamento de Datos Personales” documente esta situación, de lo contrario entenderemos que ha manifestado su pleno consentimiento para su transferencia en los términos precisados en el aviso de privacidad que nos ocupa.</p>
						<p>Asimismo, le informamos que en caso de que<strong>&nbsp;RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>, pretenda transferir sus datos personales sensibles a los terceros aquí precisados para las finalidades anteriormente descritas en el presente apartado, previo a su transferencia solicitará su consentimiento expreso y por escrito, de conformidad con la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, su Reglamento y demás disposiciones secundarias obligatorias, de lo contrario no hará uso de los mismos para estos fines.</p>
						<p>En este sentido,&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.&nbsp;</strong>le informa que, de conformidad con lo dispuesto por el artículo 37 de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, podrá transferir sus datos personales, sin su consentimiento, en los casos que a continuación se especifican:</p>
						<figure class="wp-block-table"><table><tbody><tr><td>•</td><td>Cuando la transferencia esté prevista en una Ley o Tratado en los que México sea parte.</td></tr><tr><td>•</td><td>Cuando la transferencia sea necesaria para la prevención o el diagnóstico médico, la prestación de asistencia sanitaria, tratamiento médico o la gestión de servicios sanitarios.</td></tr><tr><td>•</td><td>Cuando la transferencia sea efectuada a sociedades controladoras, subsidiarias o afiliadas bajo el control común del responsable, o a una sociedad matriz o a cualquier sociedad del mismo grupo de<strong>&nbsp;RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.&nbsp;</strong>que opere bajo los mismos procesos y políticas internas.</td></tr><tr><td>•</td><td>Cuando la transferencia sea necesaria por virtud de un contrato celebrado o por celebrar en interés del titular de datos, por<strong>&nbsp;RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.&nbsp;</strong>y un tercero.</td></tr><tr><td>•</td><td>Cuando la transferencia sea necesaria o legalmente exigida para la salvaguarda de un interés público, o para la procuración o administración de justicia.</td></tr><tr><td>•</td><td>Cuando la transferencia sea precisa para el reconocimiento, ejercicio o defensa de un derecho en un proceso judicial.</td></tr><tr><td>•</td><td>Cuando la transferencia sea precisa para el mantenimiento o cumplimiento de una relación jurídica entre&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>&nbsp;y el titular de datos.</td></tr></tbody></table></figure>
						<p><strong>MECANISMOS Y PROCEDIMIENTOS PARA LA REVOCACIÓN DEL CONSENTIMIENTO AL TRATAMIENTO DE DATOS PERSONALES Y/O EJERCICIO DE DERECHOS ARCO.</strong></p>
						<p>En todo momento usted podrá revocar el consentimiento que nos ha otorgado para el tratamiento de sus datos personales, a fin de que dejemos de hacer uso de los mismos. Sin embargo, es importante que tenga en cuenta que no en todos los casos podremos atender su solicitud o concluir su uso de forma inmediata, ya que es posible que por alguna obligación legal requiramos seguir tratando sus datos personales. Asimismo, usted deberá considerar que para ciertos fines, la revocación de su consentimiento implicará que no le podamos seguir prestando el servicio que nos solicitó, o la conclusión de su relación con nosotros.</p>
						<p>Para revocar su consentimiento deberá acudir a nuestras oficinas y solicitar el “Formato de solicitud de revocación del consentimiento”, acompañando a dicha solicitud los documentos que acrediten su identidad (identificación oficial) o, en su caso, de quien legalmente le represente. Asimismo, usted podrá solicitar dicho formato a nuestro “Departamento de Datos Personales”, a través del correo electrónico&nbsp;<a href="https://shampoohuichol.com/index.php/contactanos/">jose_heredia@ziloe.com.mx</a>&nbsp;o al teléfono (33) 36272405.</p>
						<p>Asimismo, usted tiene derecho a acceder, rectificar, cancelar u oponerse al tratamiento de sus datos personales (derechos ARCO). En este sentido, como titular de sus datos personales tiene el derecho de conocer qué datos personales mantiene<strong>&nbsp;RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>, para qué los utilizamos y las condiciones del uso que les damos (Acceso), así como a rectificarlos en caso de ser inexactos, desactualizados o incompletos (Rectificación), instruirnos a cancelarlos cuando estos resulten excesivos o innecesarios para las finalidades descritas que justificaron su obtención, considere que los mismos no están siendo utilizados conforme a los principios, deberes y obligaciones previstas en la normativa aplicable (Cancelación), o bien, oponerse al uso de sus datos personales para fines específicos (Oposición), en los casos en que la Ley Federal de Protección de Datos Personales en Posesión de los Particulares así lo permita.</p>
						<p>Para ejercer los derechos ARCO conforme lo mencionado en el párrafo anterior, podrá acudir a nuestras oficinas y solicitar el “Formato de solicitud de derechos ARCO”, acompañando a dicha solicitud los documentos que acrediten su identidad (identificación oficial) o, en su caso, de quien legalmente le represente. Asimismo, usted podrá solicitar dicho formato a nuestro “Departamento de Datos Personales”, a través del correo electrónico&nbsp;<a href="https://shampoohuichol.com/index.php/contactanos/">jose_heredia@ziloe.com.mx</a></p>
						<p><strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.&nbsp;</strong>atenderá su petición en los tiempos estipulados en las leyes aplicables y le informará de las consecuencias que deban producirse con motivo del ejercicio de su derecho.</p>
						<p>Para conocer puntualmente el procedimiento establecido por<strong>&nbsp;RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.&nbsp;</strong>para la revocación del consentimiento respecto del tratamiento de sus datos personales y/o respecto del ejercicio de los derechos ARCO, usted podrá acudir personalmente a nuestra oficinas y contactar al “Departamento de Datos Personales”, así como contactarlo a través del correo electrónico&nbsp;<a href="https://shampoohuichol.com/index.php/contactanos/">jose_heredia@ziloe.com.mx</a>, donde con gusto le informaremos sobre los detalles del procedimiento y requisitos para el ejercicio de sus derechos.</p>
						<p>Si considera que no ha recibido una respuesta de<strong>&nbsp;RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.&nbsp;</strong>o bien la respuesta que se le dio no es satisfactoria, usted tiene el derecho de acudir al Instituto Nacional de Transparencia, Acceso a la Información y Protección de Datos Personales (INAI) a presentar una solicitud de protección de datos dentro de los quince días siguientes a la fecha en que venza el plazo para que&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.&nbsp;</strong>de respuesta a su solicitud de conformidad con la Ley Federal de Protección de Datos Personales en Posesión de los Particulares y su Reglamento, así como del procedimiento que hemos instaurado para ello, o bien, de la respuesta que hubiésemos dado a la misma.</p>
						<p><strong>MEDIOS PARA LIMITAR EL USO O DIVULGACIÓN DE LOS DATOS PERSONALES</strong><br><strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>&nbsp;le informa que, con el objeto de que usted pueda limitar el uso o divulgación de sus datos personales, ponemos a su disposición la dirección de correo electrónico&nbsp;<a href="https://shampoohuichol.com/index.php/contactanos/">jose_heredia@ziloe.com.mx</a>, a efecto de ser inscrito en nuestro listado de exclusión denominado “Contactos que no desean envío de publicidad”, a fin de que sus datos personales no sean tratados para fines mercadotécnicos, publicitarios o de prospección comercial, así como para evaluación de nuestros productos y servicios relacionados con las marcas Shampoo Huichol por nuestra parte.</p>
						<p><strong>USO DE COOKIES, WEB BEACONS U OTRAS TECNOLOGÍAS</strong><br><strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.&nbsp;</strong>le informa que, podrá utilizar mecanismos en medios remotos o locales de comunicación electrónica, óptica u otra tecnología; tales como&nbsp;<em>cookies</em>&nbsp;y&nbsp;<em>web beacons</em>, que permitan recabar diversos datos de manera automática y simultánea al tiempo que usted como consumidor o posible consumidor hace contacto con los mismos. Si quieres tener más información, por favor, consulta nuestra&nbsp;<a href="https://naturistasziloe.com/index.php/politica-de-privacidad/">Política de Privacidad</a>, donde podrás revisar cómo desactivarlos y en su caso,&nbsp;<a href="https://naturistasziloe.com/index.php/politica-de-privacidad/">qué&nbsp;<em>cookies</em>&nbsp;estamos usando</a>&nbsp;para recabar tus datos personales.</p>
						<p>Los&nbsp;<em>cookies</em>&nbsp;son aquellos archivos de datos que se almacenan en el disco duro del equipo de cómputo o del dispositivo de comunicaciones electrónicas de un usuario al navegar en un sitio de Internet específico, el cual permite intercambiar información de estado entre dicho sitio y el navegador del usuario. La información de estado puede revelar en algunos casos medios de identificación de sesión, autenticación o preferencias del usuario, así como cualquier otro dato almacenado por el navegador respecto del sitio de Internet.</p>
						<p>Se entiende por web&nbsp;<em>beacons</em>&nbsp;a aquella imagen visible u oculta insertada dentro de un sitio web o correo electrónico, que se utiliza para monitorear el comportamiento del usuario en estos medios. A través de éstos se puede obtener información como la dirección IP de origen, navegador utilizado, sistema operativo, momento en que se accedió a la página, y en el caso del correo electrónico, la asociación de los datos anteriores con el destinatario.</p>
						<p>En concreto,<strong>&nbsp;RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>, utilizará&nbsp;<em>cookies</em>&nbsp;y&nbsp;<em>web beacons</em>&nbsp;al enviar correos electrónicos con información relacionada con las Marcas, ya que al momento en que usted reciba y, en su caso, lea alguno de nuestros correos, por medio de estas tecnologías podremos recabar los siguientes datos:</p>
						<figure class="wp-block-table"><table><tbody><tr><td>i)</td><td>Conocer si abrió o no el correo electrónico que le enviamos y;</td></tr><tr><td>ii)</td><td>Conocer si accedió o no a la(s) liga(s) o URL(s) contenidas en el correo.</td></tr></tbody></table></figure>
						<p>Asimismo, le informamos que los datos que se obtienen a través de estas tecnologías se utilizarán exclusivamente para fines estadísticos y de revisión de resultados, sin que exista la posibilidad de transferirlos a terceros.</p>
						<p>La mayoría de los exploradores acepta las cookies automáticamente. Aun así, es posible configurar cualquier explorador para evitar que acepte cookies e impedir de este modo que su equipo o dispositivo las almacene. Algunos exploradores cuentan con un modo especial que garantiza la eliminación de las cookies tras una visita. Consulte el manual de su explorador si desea conocer los pasos exactos que permiten activar el modo correspondiente. Puede eliminar las cookies que se encuentren almacenadas en su equipo o dispositivo en cualquier momento.</p>
						<p>En este sentido, en apoyo a usted y para ejemplificarlo establecemos la forma en que se pueden deshabilitar las cookies en el navegador&nbsp;<em>Internet Explorer</em>&nbsp;y que son las siguientes:&nbsp;<em>i)</em>&nbsp;Abrir en su computadora el navegador&nbsp;<strong>Internet Explorer</strong>.&nbsp;<em>ii)</em>&nbsp;Al ingresar hacer&nbsp;<em>click</em>&nbsp;en el botón&nbsp;<strong>Herramientas</strong>&nbsp;y después en&nbsp;<strong>Opciones de Internet</strong>&nbsp;y&nbsp;<em>iii)</em>&nbsp;Posteriormente hacer&nbsp;<em>click</em>&nbsp;en la ficha&nbsp;<strong>Privacidad</strong>, y a continuación, en&nbsp;<strong>Configuración</strong>, mueva el control deslizante totalmente hacia arriba para bloquear todas las cookies o totalmente hacia abajo para permitir todas las cookies y, a continuación, haga clic en&nbsp;<strong>Aceptar</strong>.</p>
						<p>En ningún otro caso,&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.&nbsp;</strong>utilizará este tipo de tecnologías. En caso contrario, lo hará de su conocimiento previamente.</p>
						<p><strong>MODIFICACIONES Y CAMBIOS AL AVISO DE&nbsp;PRIVACIDAD<br></strong>Este aviso de privacidad podrá ser modificado o actualizado de tiempo en tiempo por&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>&nbsp;modificación.</p>
						<p>Fecha de Publicación: Noviembre 2023<br>Fecha de última actualización: Noviembre 2023</p>
					</div>
				</div>
			</div>
		</section>
		<?php include "_footer.php";?>
		<?php include "_js.php";?>
		<script>
			
		</script>
	</body>
</html>