<!doctype html>
<html lang="es">
	<?php include "_head.php";?>
	<body>
		<?php include "_header.php";?>
		<section class="encuesta">
			<div class="container">
				<div class="row mb-5">
					<div class="col text-center">
						<h1>Términos y Condiciones</h1>
					</div>
				</div>
				<div class="row mb-5">
					<div class="col">
						<p><strong>Lee atentamente las condiciones estipuladas a continuación antes de utilizar el presente sitio web.</strong></p>
						<p><strong>Términos y Condiciones de Uso</strong></p>
						<p><strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>, DISTRIBUIDOR de la marca Naturistas Ziloé, (en adelante la “Marca”) se complace en darte la bienvenida a su sitio web, al que puede accederse en la siguiente dirección URL: www.naturistasziloe.com (en lo sucesivo, denominado el «Sitio»), o bien en cualquier otra URL, hipervínculo, pestaña o botón incluido en otro sitio que dirija al Sitio. El Sitio ha sido desarrollado y/o editado por<strong>&nbsp;RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>, con domicilio convencional en Calle Chicle #674, Col. Glorias del Colli en Ciudad de Zapopan, Jalisco y se rige por condiciones específicas de uso, mismas que serán de aplicación a aquellas páginas editadas por&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong></p>
						<p>Al acceder al Sitio, cualquier persona que esté navegando, utilice y permanezca en él (en lo sucesivo, denominado el «Usuario») declara haber leído y aceptado sin reserva alguna las presentes condiciones de uso, se compromete a ajustarse a ellas y a cumplir las disposiciones previstas a continuación en cualquier circunstancia:</p>
						<p><strong>1. DERECHO DE PROPIEDAD INTELECTUAL RELATIVO AL SITIO</strong></p>
						<p>El Sitio es una obra de creación intelectual protegida por la legislación en materia de propiedad intelectual y/o derechos de autor. Tanto el Sitio como los elementos que lo componen (marcas, logotipos, fotografías, imágenes, ilustraciones, textos, clips de vídeo y similares, entre otros) constituyen propiedad exclusiva de&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>, que es la única facultada para utilizar los derechos personales y de propiedad intelectual asociados al mismo, y que no otorga ninguna licencia ni otro tipo de derecho exceptuando el de consultar el Sitio en el marco de un uso con fines estrictamente privados.</p>
						<p>La reproducción de los eventuales documentos publicados en el Sitio se autoriza únicamente a efectos exclusivamente informativos, en el marco de un uso estrictamente personal y privado. Se prohíbe de forma expresa cualquier reproducción y/o representación total o parcial del Sitio, o de cualquiera de los elementos que lo componen, en cualquier soporte, a otros efectos, y en particular a efectos comerciales.</p>
						<p>Exceptuando los supuestos indicados anteriormente,&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.&nbsp;</strong>deberá autorizar de forma previa y expresa cualquier otra reproducción y/o representación del Sitio y/o del contenido del Sitio. En este sentido, las solicitudes de autorización deben remitirse a la siguiente dirección de correo electrónico: jose_heredia@ziloe.com.mx el entendido de que reproducir total o parcialmente el Sitio o el contenido del Sitio, constituirá una violación a los derechos de propiedad intelectual, incluyendo los derechos de autor de<strong>&nbsp;RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>, por lo que éste se encontrará facultado de ejercitar cuantas acciones administrativas o judiciales haya a lugar, incluyendo proceder por la vía penal contra quien infrinja la presente disposición.</p>
						<p><strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.&nbsp;</strong>no asume ninguna responsabilidad en relación con el contenido, publicidad, productos o servicios disponibles en los sitios vinculados al Sitio o a partir de ellos. Asimismo, todas las marcas mencionadas en el Sitio son marcas registradas y, por tanto, protegidas por lo que<strong>&nbsp;RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>&nbsp;deberá autorizar de forma previa y expresa, por escrito, cualquier uso de dichas marcas.</p>
						<p>En cualquier caso,&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.&nbsp;</strong>recuerda a los Usuarios que las solicitudes de autorización deben remitirse a la siguiente dirección de correo electrónico: jose_heredia@ziloe.com.mx</p>
						<p><strong>2. ACCESO AL SITIO</strong></p>
						<p><strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>&nbsp;hará todo lo posible por garantizar la accesibilidad del Sitio, aunque no está sujeta a ninguna obligación en dicho sentido. Se precisa que podrá interrumpirse el acceso al Sitio a efectos de mantenimiento y actualización, así como por otros motivos, especialmente de carácter técnico; por lo cual no se responsabilizará en ningún caso por dichas interrupciones ni de las consecuencias que éstas puedan generar para el Usuario, aunque sí tratará, en la medida de lo posible, de minimizar las molestias ocasionadas por estas operaciones.</p>
						<p>En cualquier caso,<strong>&nbsp;RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.&nbsp;</strong>hará todo lo que está a su alcance para proporcionar contenidos y servicios de calidad y adaptados a los sistemas informáticos estándar presentes en el mercado, aunque en ningún caso garantiza la inexistencia de errores, defectos o vicios de diseño que puedan imposibilitar su uso y/o instalación, por lo que no se responsabilizará en ningún caso de las consecuencias, directas o indirectas, y/o de los eventuales daños provocados por defectos en el Sitio y/o contenido del mismo.</p>
						<p><strong>3. UTILIZACIÓN DEL CONTENIDO DEL SITIO.</strong></p>
						<p>Las opiniones, imágenes y demás contenido expresado anteriormente, no representa la opinión ni posicionamiento de Shampoo Huichol y/o Naturistas Ziloé, por lo que las ideas antes expresadas son responsabilidad de quien las emite.</p>
						<p>a) Disposiciones Generales<br><br><strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.&nbsp;</strong>hará todo lo posible por actualizar el contenido del Sitio y ofrecer a los Usuarios información precisa. No obstante, el Usuario reconoce que las transmisiones de datos e información en Internet poseen una fiabilidad técnica relativa, ya que circulan por redes heterogéneas. Por tanto,<strong>&nbsp;RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>&nbsp;no está en condiciones de garantizar la precisión de los datos incluidos en el Sitio. Los eventuales errores u omisiones deben notificarse a la siguiente dirección de correo electrónico: josé_heredia@ziloe.com.mx. Así mismo, si hubiera la necesidad de contactar con los administradores del contenido por cualquier tema referido con la información, contenido o cualquier otro tema referente por favor contactar al número telefónico: (33) 3627 2405.</p>
						<p>Cualquier uso del Sitio no conforme con su planteamiento original o infracción de las presentes disposiciones podrán generar la imposición de sanciones administrativas, penales y civiles previstas por la legislación.</p>
						<p>b) Contenido Descargable<br><br>En el Sitio,&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.&nbsp;</strong>podrá poner a disposición de los Usuarios, contenidos descargables (en lo sucesivo, denominados los «Contenidos Descargables»), que se identifican de forma explícita como tales con la mención «Descarga» o una pestaña específica a tales efectos. Al utilizar y/o descargar Contenidos Descargables disponibles en el Sitio, el Usuario reconoce haber sido informado de que estos se proporcionan «tal cual» y que su descarga y/o uso se realizan a su cuenta y bajo su riesgo</p>
						<p>Haciendo clic en el botón «descargar» o al descargar, instalar, copiar o utilizar Contenidos Descargables, el Usuario se compromete a utilizarlos con arreglo a las condiciones previstas a continuación:</p>
						<p>(i)Licencia<br><br><strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.&nbsp;</strong>otorga al Usuario, a título gratuito y durante la vigencia legal de la protección de los derechos de autor, un derecho de uso personal, no exclusivo e intransferible en relación con los Contenidos Descargables a efectos exclusivamente personales y privados.</p>
						<p>Así pues, se autoriza al Usuario a reproducir y representar Contenidos Descargables para un uso exclusiva y estrictamente personal y privado. Se prohíbe de forma expresa cualquier reproducción, edición, alteración y/o representación, total o parcial, de Contenidos Descargables para cualquier fin distinto al establecido en los presentes términos de uso, específicamente para fines comerciales tales como de mercadotecnia, publicidad o prospección comercial, supuesto en el cuál, según lo previsto en la legislación vigente, aquél que haga uso de imágenes protegidas por derecho de autor para los fines señalados, deberá pagar el 30% (treinta por ciento) de las utilidades netas de la comercialización del producto en cuestión. El Usuario reconoce que no posee ningún otro tipo de derecho exceptuando los otorgados con arreglo a las disposiciones de la presente en materia de Contenidos Descargables.<br><br>Excepto en los supuestos indicados anteriormente&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>&nbsp;deberá autorizar de forma previa y expresa cualquier reproducción y/o representación de contenidos. En este sentido, las solicitudes de autorización deben remitirse a la siguiente dirección de correo electrónico: jose_heredia@ziloe.com.mx</p>
						<p>(ii) Lealtad<br><br>El Usuario se compromete a utilizar los Contenidos Descargables de forma leal.</p>
						<p>c) Vínculos de hipertexto instalados en el Sitio<br>Los vínculos de hipertexto instalados en el Sitio pueden conducir al Usuario a sitios web de diferentes socios. A este respecto, se precisa que&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>&nbsp;no ha verificado todos los sitios que puedan estar vinculados al suyo, como tampoco su contenido ni la información incluida en ellos, y por tanto no asume ninguna responsabilidad en relación con el contenido de dichos sitios y con el uso realizado por el Usuario de ellos. El Usuario se responsabiliza a título exclusivo del uso de estos sitios.</p>
						<p><strong>4. JURISDICCIÓN APLICABLE Y RESOLUCIÓN DE CONTROVERSIAS</strong></p>
						<p>Las presentes condiciones de uso del Sitio se rigen por el Derecho Mexicano.</p>
						<p>Las eventuales controversias relativas a la validez, interpretación y/o ejecución de los presentes términos y condiciones de uso serán sometidas a la jurisdicción de los juzgados y tribunales competentes ubicados en la Ciudad de México, sin importar el domicilio actual o futuro del demandante.</p>
						<p><strong>5. USO DE COOKIES</strong></p>
						<p>Las cookies y otros dispositivos de almacenamiento en local son pequeños ficheros depositados en el ordenador de los visitantes del Sitio, que registran información relativa a la navegación de éste por el Sitio (las subpáginas, links y artículos consultados, la fecha, tiempo y hora de visita), información que puede leerse en visitas posteriores al Sitio.</p>
						<p>Al navegar por este sitio web se utilizan cookies de sesión y cookies persistentes que a su vez pueden ser cookies propias o de terceros.</p>
						<p>Se recuerda al Usuario que este puede impedir el registro de cookies configurando su navegador a tales efectos. No obstante, para beneficiarse de todas las funciones del Sitio, se recomienda configurar el navegador para que acepte las cookies del Sitio, que han sido diseñadas para el uso exclusivo de&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong></p>
						<p><strong>RAFAEL BERRUETA SORIANO</strong>&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>&nbsp;reglamentarias o con la finalidad de adaptar dicha política a las instrucciones dictadas por el Instituto Nacional de Transparencia, Acceso a la Información y Protección de Datos Personales (INAI).</p>
						<p>Para más información respecto el uso de cookies consultar nuestro&nbsp;<a href="https://naturistasziloe.com/index.php/politica-de-privacidad/">Aviso de Privacidad</a>.</p>
						<p><strong>6. PROTECCIÓN DE DATOS PERSONALES</strong></p>
						<p>De acuerdo a la Ley Federal de Protección al Consumidor en las transacciones efectuadas a través del uso de medios electrónicos, ópticos o de cualquier otra tecnología,&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>&nbsp;se obliga a utilizar la información proporcionada por usted en su carácter de usuario, de forma confidencial, por lo que no podrá difundirla o transmitirla, salvo que se haya otorgado su consentimiento expreso para dicho efecto.</p>
						<p>Todos los datos personales y datos personales sensibles que el Consumidor proporcione a&nbsp;<strong>RAFAEL BERRUETA SORIANO y/o NATURISTAS ZILOÉ S.A. DE C.V.</strong>&nbsp;a través de éste sitio será tratada como estrictamente confidencial de conformidad con nuestro Aviso de Privacidad.</p>
						<p>Los presentes Términos y Condiciones podrán variar sin responsabilidad y sin previo aviso, por lo que el usuario deberá revisarlos de tiempo en tiempo, siendo los publicados en el Sitio los Términos y Condiciones vigentes.</p>
						<p>Publicación: Noviembre de 2023</p>
						<p>Última modificación: Noviembre de 2023</p>
					</div>
				</div>
			</div>
		</section>
		<?php include "_footer.php";?>
		<?php include "_js.php";?>
		<script>
			
		</script>
	</body>
</html>